# Generated by Django 4.1.1 on 2022-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_managers_remove_usermodel_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(default='', max_length=256),
        ),
    ]
